### ISSUE TITLE
Swift 4.2 compatibility

### ISSUE THREAD

**Issue by EBMCreative** [luispadron/UICircularProgressRing#106]
Looking for swift 4.2 compatibility as Carthage will not install framework as it was built with swift 4.1.2

Thanks

**Comment by luispadron** [comment]
I’ll release a build for 4.2 when it’s out of beta, as of right now it doesn’t make sense to force people into Xcode 10 since Carthage only allows one framework archive to be used. 

Carthage should be able to build the framework from the source project though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EBMCreative** [comment]
Sounds great. Thanks.

**Comment by shardul89** [comment]
@luispadron any updates here. Waiting for Swift 4.2 support.

**Comment by luispadron** [comment]
Sorry been really busy with school. I’ll try to get a build out today.

**Comment by luispadron** [comment]
#137 should be merged soon

**Comment by ArturGasparyan** [comment]
@luispadron, for some reason I still cannot build with Xcode 10 and Swift 4 (not 4.2). However the error complains about 4.2 compatibility: `Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'easeInEaseOut'`

There are 8 more errors of the same type, like

`willEnterForegroundNotification' has been renamed to 'NSNotification.Name.UIApplicationWillEnterForeground'` and so forth.

Do you know, how to make this work again, since you claim, that you have support for Swift 4.2? I'm using Using UICircularProgressRing (4.1.0).

Help is highly appreciated, thank you.

**Comment by luispadron** [comment]
@ArturGasparyan Have you looked at the other issues that have already been made about this? #147 in particular.

The latest version of this project requires Swift 4.2.

**Comment by ArturGasparyan** [comment]
Hey @luispadron, thank you for your answer. Well, I had to upgrade the whole project to 4.2, which was a greater hustle than expected. But this way your library seems to work. Didn't appear usual to drop the support for .0 and require .x instead, seem to have missed the requirement.

**Comment by Rj707** [comment]
@luispadron even the latest version 6.0 is having some issue with swift 4.2

**Comment by Rj707** [comment]
Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'easeInEaseOut'
