### ISSUE TITLE
Animation stops after pushing to new view controller

### ISSUE THREAD

**Issue by kamarshad** [luispadron/UICircularProgressRing#151]
#### Version

3.3.2

Hello @luispadron 

I am displaying a circular progress ring animation on a view controller(let say OverViewController). 
And that VC has a button by tapping on it I can push another view controller (let say DetailViewController). As soon I push to DetailViewController and pop back to the OverViewController circular progress set to maximum progress value automatically(which shouldn't be happened) as there was a lot of time left to reach the maximum progress value. I double checked my source code and there was nothing which could hamper its behaviour I don't know but someway animation stopping automatically.

- The `current value` of the progress ring will be updated in real time if the ring is animating. If the ring is not currently animating then the value returned will be the `value` property of the ring.
- Calling `startProgress` method again while a current progress animation is in progress will **not**
     cause the animation to be restarted. The old animation will be removed (calling the completion and delegate) and a new animation will start from where the old one left off at. 

As both of the properties `value` and `currentValue` are read-only can't reset as soon popped back to OverViewController(By somehow keeping the remaining progress and time and resuming it from there) and also tried re-calling `startProgress`method but nothing worked. Even progress ring animation won't start until I re-instantiate the circular progress ring.

#### What is the expected outcome?
The circular progress animation should be running and it shouldn't reach the maximum progress value immediately as I push DetailViewController.  

#### What is the actual outcome?
The circular progress ring animation progress stops immediately and updates to maximum progress value as I push DetailViewController.

#### Post sample code or example here
Circular progress ring view is being created from storyboard and below is the basic setup code
```swift
        self.circleProgressView.startAngle = -90
        self.circleProgressView.outerRingColor = .clear
        self.circleProgressView.innerRingWidth = 2.0
        self.circleProgressView.innerRingColor = .blue
        self.circleProgressView.shouldShowValueText = false
        self.circleProgressView.delegate = self
```
Using below peice of code to start the progress ring animation.

```swift
self.circleProgressView.startProgress(to: 100, duration: 60) {
            print("Progress completed!")
        }
```
I have a demo application and if you want  I can share it with you.
Looking forward to your help.

**Comment by kamarshad** [comment]
@luispadron Thank you for your comment. I just forwarded the demo application. Kindly check your inbox.

Thanks

**Comment by luispadron** [comment]
Hi again, just took a look at your example you emailed me thanks a lot again for this it really helps debug.

This actually is not a bug. Let me explain, when you push a view controller CALayerAnimations will be removed from the view, it is not possible to keep them animating. This is why there are methods on the progress ring to help you do just this.

To "fix" this issue in your project simply do something like this:

```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        // continue if it was paused
        self.circleProgressView.continueProgress()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        // pause, IMPORTANT to do this
        self.circleProgressView.pauseProgress()
    }
```

The key here, is you need to call `pauseProgress` so that the ring saves the animation layer and can then reuse that layer when we `continueProgress`. Make sure to call `continueProgress` and not `startProgress` as this will just restart everything.

I recommend looking at the documentation if you still have issues with this.

**Comment by kamarshad** [comment]
Thank you @luispadron  for your time.
But it is almost impossible to achieve continuous animation if pause and continue progress.

What if the Library has some interface to update the `current value` and after as soon we call `pauseProgress` it resumes the animation at the updated current value.

**Comment by luispadron** [comment]
Im not sure what you mean?

**Comment by dvlpd** [comment]
I have the same issue, however it happens under different circumstances.
I have a view controller page with timer. And this view controller is one of 3 inside Tab Bar View Controller. It happens either when I go to the other page inside Tab Bar View or when my app enters background.
The problem is that I need my timer and hence my UICircularProgressRing to run both when app enters background and when I go to the other view controller inside my app

**Comment by dvlpd** [comment]
Unfortunately the solution presented here doesn't help me, as the animation should match the time that is left. Thanks in advance!

**Comment by dvlpd** [comment]
@luispadron

**Comment by luispadron** [comment]
Hey there @dvlpd, I'm not 100% sure what your question is. I can take a closer look, please file a new ticket and provide as much details as possible. Sample code with issue reproduction is the best, I can't solve the issue otherwise.
