### ISSUE TITLE
Pod requires target of iOS 10.0  

### ISSUE THREAD

**Issue by DannyJi** [luispadron/UICircularProgressRing#2]
I cannot use this on a new app I am building because our client wants our app to work with both iOS9 and iOS10.  Is iOS 10, necessary for this pod?  I see that in your pod spec.

When I run pod install with:
 ` platform :ios, '9.0'`

I get  an error  about `UICircularProgressRing`required a higher minimum deployment target.

If i run this with 
   `platform :ios, '10.0'`

I can install properly

**Comment by luispadron** [comment]
Hey, just updated to remove the 10.0 requirement. 
This was here because of the early days of Xcode beta and totally forgot to remove it.

This library doesn't require anything specific to 10.0, so don't see issues with 9.0, however I've only tested on the newest iOS.

I am glad you want to use the library, may I ask if the application you're working on is open to the public, then once you finish please come back here and provide a link so that I may showcase the use of the library in an actual production app. I'd really appreciate it.

[Go here for the new changes](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.1.0)

or just run `pod update`

**Comment by DannyJi** [comment]
Thanks!  I did play around with this for a bit this afternoon.  When I did use the target of iOS10, I was able to install (as mentioned).  However, the migration assistant in Xcode 8 complained a bit for Swift 3.0.  I fixed the necessary code and it worked.

However, while you were fixing pod spec, I started using another similar project MBCircularProgressBar.  It's in Objective-C.  If I have time this week, I will retry yours as I like the customizations.  I'll note if I have any Swift 3 migration issues again.

I cannot tell about the app we are using it in ATM due to client restrictions.  When it is released, I will surely let you know and provide a link.

**Comment by luispadron** [comment]
@DannyJi 

This project is written in Swift 3, however I've also noticed how Xcode complains about updating project settings and such.
Adding this line to the end of your `Podfile` will likely fix the issue

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = "3.0"
    end
  end
end
```

**Comment by mthuong** [comment]
@luispadron Could we have iOS 8.0 support for cocoapod?

**Comment by luispadron** [comment]
@mthuong I lowered the podspec version, now allows iOS 8.0 

[Version 1.1.6](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.1.6)
