### ISSUE TITLE
Simulate Indeterminate State

### ISSUE THREAD

**Issue by mazz** [luispadron/UICircularProgressRing#203]
## Version

- Version = 6.2.0

## Details

How does one simulate an indeterminate progress? What I mean is something like progress == 1.0 and the circle gradient is animating. Or possibly a full progress dashed ring that is rotating/animating. 

  - ANSWER HERE

**Comment by luispadron** [comment]
Hi there. 

That’s not the intended purpose of this library, as this is more for showing the progress of a task. It’s possible, using the provided methods you can create a timer and reset and start the rings animations as needed. I feel this would be more work than finding a good library (there are tons) that do what you’re looking for. 

Sorry I can’t provide the code to do this at this moment, since I am away from a computer.

**Comment by mazz** [comment]
Thanks for the feedback.
