### ISSUE TITLE
Can I change value of "valueLabel"?

### ISSUE THREAD

**Issue by goktugaral** [luispadron/UICircularProgressRing#35]
Hi,
Thanks for this library. In my project, I have to set different value to valueLabel, in example "45+".
But because of private, it can't be done.

> lazy private var valueLabel: UILabel = UILabel(frame: CGRect(x: 0, y: 0, width: 0, height: 0)) 

Could you add this improvement please.

Thank you.

**Comment by luispadron** [comment]
The label is private because it's attributes are updated based on the `value` of the progress ring. 

When you call `setProgress` the labels text will get updated to the value you send. If you want the _+_ at the end of a value you can use the `valueIndicator` property of the progress ring.

You can try something like this to get your desired look.

```swift
// Assuming ring is a UICircularProgressRing
ring.valueIndicator = "+"
ring.setProgress(value: 45, animationDuration: 0)
```

Let me know if this is what you meant. I can see an improvement might be having a static label and having only the progress ring animate and change. So let me know if the above solution works for you, or if what you wanted was more of a _static label_

**Comment by goktugaral** [comment]
@luispadron thanks for your quick response. I might thought static label but actually your suggestion solved my problem. Also it removed "%" at end. Thank you so much! :) 👍

**Comment by mrugeshtank** [comment]
How can I set more values then progress?
like, I'm creating drinking water app, if user drinks more then goal, then how can I display within animated circular?
