### ISSUE TITLE
Need help with property currentValue

### ISSUE THREAD

**Issue by nordinFreeCodeCamp** [luispadron/UICircularProgressRing#42]
- Version = 1.6.1

#### Have you read the documentation?

- [X] Yes 
- [ ] No
 
#### Is it a bug? 

I am not sure that it's bug

#### Is it a question? Provide the following

In my app, I am using UICircularProcessing. It is working really good and easy to understand. Good job!
However, I need to do something with property currentValue but it is not working. Maybe, I am not using it correctly. I have read all your doc and code, but still need your help.

In my app, I have a label that I want to update each time the UICircularProcessing made a progress. So as I read in your doc, property currentValue can give this information in realtime. But I didn't succeed with it. Below I share with you a small code on how I am trying to do that, I am certainly not using it in the correct way :-)

`
        
        
        circularProgressView.setProgress(value: 535, animationDuration: 10)
        DispatchQueue.global(qos: .background).async {
            while self.circularProgressView.isAnimating {
                print(self.circularProgressView.currentValue!)
            }
        }
`

So if I understand well, during animation I should get the progression of the currentValue in realtime. But the print gives me always the same value, until animation stops.

Thanks in advance for your help.

**Comment by luispadron** [comment]
This could be because you are checking the value in a background thread, and the animation is happening on the main thread. 

Give me a few hours and I’ll try to see what can be done but initial reading leads me to believe this may not be possible to observe value changes to a layer on a value per value base notification style. Current value simply queries the presentation of the layer for the value at the specific time, it is not being set constantly, only when called. 

 You can read that [here](https://stackoverflow.com/questions/1557739/observing-animated-property-changes-in-a-calayer)

**Comment by luispadron** [comment]
I believe I have figured out a solution for this, it will require a new delegate method that will get called every time the value changes. In this delegate call you could set your label, for example 

```swift
/// This gets called in real time when value is changing during animation
func didUpdateProgressValue(to newValue: CGFloat) {
    label.text = "\(newValue)"
}
```

It will take me some time to get this out as a release because I want to make sure this wont leak any memory or cause anything to slow down, as it is calling this delegate method hundreds of times a second. Let me know if this would be a good solution for your problem, I never thought about needing something like this but I can see how it would be a good feature to have for some scenarios.

**Comment by nordinFreeCodeCamp** [comment]
Thanks for your answer. I am checking the value in a background thread because otherwise the loop will block the animation. 
Regarding the solution you propose, it is what I was thinking to do to solve my problem. But I wanted to be sure that I was using the currentValue correctly before building my own solution.

And I agree with you, this good be a nice feature. My scenario is quite simple. I have a table with values, the number of values in my table will be reflected in maxValue. My goal is to update my label with the table values based on the progress of UICircularProgressRing in realtime.

I will take some time on my side to work on it and I will share with you my final solution.

Thanks again for your help.

**Comment by luispadron** [comment]
I was already done with it last night, just wanted to profile things and check for leaks. Thanks though!

The new version [1.6.2](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.6.2) is now available and should solve your problem. You can `pod update` or update the dependency as needed, I will close this issue. Please update if something goes wrong.

**Comment by nordinFreeCodeCamp** [comment]
Good job Luis!
