### ISSUE TITLE
Fix: Automatically confining ring to view bounds

### ISSUE THREAD

**Issue by recovaware** [luispadron/UICircularProgressRing#66]
If the view is not a perfect square then the rings will extend beyond the view bounds because the radii in drawOuterRing and drawInnerRing are set with max(x: _, y: _).  Should be min(x:_,y:_) to ensure the radius is not larger than the minimum view bounds.  Also, height in drawOuterRing() should be bounds.height.  

let width: CGFloat = bounds.width
let height: CGFloat = bounds.height
let center: CGPoint = CGPoint(x: bounds.midX, y: bounds.midY)
let outerRadius: CGFloat = min(width, height)/2 - max(outerRingWidth, innerRingWidth)/2

**Comment by luispadron** [comment]
That makes sense, don't currently have too much free time to work on this due to finals, but after I'll try to get this out, or feel free to send a pull request my way. 

Tests, may have to be updated however.

 As for the width and height, using frame or bounds for those two doesn't really matter as the height and width aren't dependent on which view we're talking about, even though I'm pretty sure I use bounds anyway.

Thanks for bringing this suggestion up!

**Comment by luispadron** [comment]
Fixed in [1.7.5](https://github.com/luispadron/UICircularProgressRing/releases/tag/v1.7.5) thanks for the report again!
