### ISSUE TITLE
Reset wheel to rerun

### ISSUE THREAD

**Issue by sarankup** [luispadron/UICircularProgressRing#71]
Hi,

This is awesome and I could integrate into my project quickly. I have requirement of restart the progress ring after clicking the button. The question is by clicking a button, how can I restart the progress ring again? I don't want to restart as it is progressing, only as it reaches `finishedUpdatingProgress`

Thanks in advance.

**Comment by luispadron** [comment]
Not really sure what you would like. 

The only two things that tell you the ring is done animating are the completion handler and the delegate method.

**Comment by sarankup** [comment]
Hi,

Thanks. My requirement is I want to restart or reset the ring to 0 as I click my button. Just like a stopwatch where I can reset the counter. (In fact, I don't want to stop as it run, but start again as it completes.)

**Comment by luispadron** [comment]
Well that's just a matter of calling

`progressRing.setProgress(0.0, 0.0) `

Which will reset the ring to 0 with no animation (since duration is 0, increase for animation).

You can [read the docs](https://htmlpreview.github.io/?https://raw.githubusercontent.com/luispadron/UICircularProgressRing/master/docs/Classes/UICircularProgressRingView.html)

**Comment by sarankup** [comment]
Thank you so much. It is fixed.
