### ISSUE TITLE
Possible wrong behavior of UICircularProgressRing in viewWillAppear in the navigation process

### ISSUE THREAD

**Issue by ChechkovEugene** [luispadron/UICircularProgressRing#78]
READ BEFORE POSTING AN ISSUE

_Not following these guidelines may result in me ignoring or closing your issue, please carefully read and submit an appropriate issue as it helps with time and fixes._

#### Please provide the current version of the library you are using

- Version = 

#### Have you read the documentation?

- [x ] Yes 
- [ ] No
 
	If no, read the docs [here](http://htmlpreview.github.io/?https://github.com/luispadron/UICircularProgressRing/blob/master/docs/index.html) before posting an issue

#### Is it a bug? Provide the following
- Detailed overview of what you are trying to accomplish

I want to start progress of UICircularProgressRing from  50 till 100 on second UIViewController of UINavigationViewController controllers presenting. 
So in the second UIViewController i set in viewDidAppear progress to 50 with animation duration 0 and then progress 100 with animation duration 10 .

- What is the expected outcome?

Progress of UICircularProgressRing starts from 50 and animates to 100 in 10 seconds

- What is the actualy outcome?

Progress of UICircularProgressRing starts from 0 and animates to 100 in 10 seconds

- Either post sample code, or example project where isssue can be recreated
[ProgressTest.zip](https://github.com/luispadron/UICircularProgressRing/files/1723876/ProgressTest.zip)

#### Is it a question? Provide the following

- Has it be answered [here](https://github.com/luispadron/UICircularProgressRing/issues?utf8=✓&q=) before?
- Be detailed and describe the question in detail
- If it's a question about something that is happening within your code base, either post a small amount of code, [email me](mailto:luis@luispadron.com) project if you want to keep it private, or post an example project where I can try to assist
- Please do your own research before posting any questions which may have been asked on StackOverFlow before. 
- Make sure to communicate back and keep issue updated or it will be closed

#### Is it a feature request? Provide the following

- Does it make sense to put this in the project? Why
- Is it something that can be done in a reasonable amount of time?
- Will it effect anyone currently using the lib?
- Have you tried to implement this and submit a pull request, if no, why not?

_If you have read all of this please follow the template and post the issue. Thanks for using UICiruclarProgressRing._

**Comment by luispadron** [comment]
This isn't quite so much a bug with the library as it is a limitation on UIKit.
I've tried everything I can to make this work better, but there isn't anything I can currently do about this.

What is happening, in this case, is that when you call `progressRing.setProgress(value: 50, animationDuration: 0.0)`, the view has to redraw itself to show the new 50% value. 

However, since you're immediately calling `progressRing.setProgress(value: 100, animationDuration: 10.0)` right after, what ends up happening is on the next draw cycle the ring will take it's current value, which is 100 since you called it too quickly. 

If you want to wait for the ring to redraw itself to 50% and then animate to 100, you can do this:

```swift
progressRing.setProgress(value: 50, animationDuration: 0.0) {
     // Animation completion, will be called right after redrawing, should be "instantly"
     self.progressRing(value: 100, animationDuration: 10.0) // now animate to 100
}
```

Thanks for posting a detailed issue that allowed me to look at this quickly, hope this fixes your issue, if not, please reopen.
