### ISSUE TITLE
Problems with animated properties

### ISSUE THREAD

**Issue by NikolaiSa** [luispadron/UICircularProgressRing#79]
Try the following code:

`        

    func testProgress()
    {        
        self.progressView.outerRingColor = UIColor.white
        self.progressView.outerRingWidth = 10
        self.progressView.innerRingWidth = 10

        self.progressView.animateProperties(duration: 1.0, animations: { () -> Void in
            self.progressView.outerRingWidth = 20
            self.progressView.innerRingWidth = 20

            self.progressView.outerRingColor = UIColor(alphaHex:"#38383e")
        }, completion: {
            self.progressView.outerRingWidth = 5
            self.progressView.innerRingWidth = 5

            self.progressView.animateProperties(duration: 1.0, animations: { () -> Void in
                self.progressView.outerRingWidth = 30
                self.progressView.innerRingWidth = 30
            })
        })
    }

`

It never sets the width to 5. It goes from 10 to 20, then 30. 

If you take out the second animation, it pops to 5 as expected. Basically mixing animation and non-animation doesn't work.

Also, the color just pops midway through the animation from White to grey. There's no fade.

**Comment by luispadron** [comment]
For the first issue, it's as I would expect. Since UIViews are only redrawn at certain times, setting the `outerRingWidth` and `innerRingWidth`, then immediately animating them to 30 and 30 will cause the 5 and 5 to not be shown, this is simply how UIKit draws the views.

As for the issue with the color, I have noticed this issue and have tried to fix it but was not able to. I don't exactly know why the color isn't animating smoothly. The reason I created the `animateProperties` function was to make it easier to animate properties **without** using CALayerAnimations, this way it behaves kind of like `UIView.animate`, however, to get actual support for properties in `UIView.animate` block is super hacky and I wasn't comfortable doing that as you need to hook onto the background color changes of the view and then animate your own properties. 

Here is this post on it: https://blog.codecentric.de/en/2016/07/custom-property-uiview-block-animation/ 

Sadly, I don't see an obvious fix for the color animation at the moment since I'm too busy with school.

**Comment by NikolaiSa** [comment]
I don't think that is correct.

Consider the following code:

    `
    func testProgress()
    {
        self.progressView.alpha = 1.0
        
        UIView.animate(withDuration: 1.0, delay: 0.0, options: .curveEaseInOut, animations: 
        { () -> Void in
            self.progressView.alpha = 0.0
        }, completion: 
        { (b: Bool) -> () in
            self.progressView.alpha = 1.0
        
            UIView.animate(withDuration: 1.0, delay: 0.0, options: .curveEaseInOut, animations: { () -> Void in
                self.progressView.alpha = 0.0
            })
        })
    }
`

Setting the alpha value to 1.0 outside the animation correctly changes the "fromValue". In your implementation, it doesn't.

**Comment by luispadron** [comment]
I see what you mean, I've been testing this out and the property does get set, that is, the values of the widths becomes 5. It just doesn't get drawn in time to be displayed before the next change to the widths in the final animation block.

I'm going to mark this as a bug, and try to figure out a way to fix this, if you want to take a stab at it as well, please feel free as it may take me longer.
